version: '3.8'

services:
  db:
    image: mysql
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 1s
      timeout: 20s
      retries: 10
      start_period: 10s
    environment:
      - MYSQL_ROOT_USER=root
      - MYSQL_ROOT_PASSWORD=1jvc19Dk
      - MYSQL_DATABASE=database_development
      - MYSQL_USER:root
      - MYSQL_PASSWORD:1jvc19Dk
    ports:
      - '3306:3306'
    volumes:
      - ./databases:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - '8880:8080'

  redis:
    image: redis
    command: /bin/sh -c "redis-server --requirepass $$REDIS_PASS"
    restart: always
    env_file:
      - .env
    ports:
      - '6779:6779'

volumes:
  databases: