version: '3.8'

services:
  db:
    image: mysql
    restart: always
    environment:
      - MYSQL_ROOT_USER=root
      - MYSQL_ROOT_PASSWORD=1jvc19Dk
      - MYSQL_DATABASE=nest_db
      - MYSQL_USER:root
      - MYSQL_PASSWORD:1jvc19Dk
    ports:
      - 3306:3306

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
